### ISSUE TITLE
Name of this repo?

### ISSUE THREAD

**Issue by kripken** [WebAssembly/musl#1]
You called this "WebAssembly/musl", which suggests it is intended to be the official musl port for WebAssembly? But have we all discussed and agreed that we will have a single such port, and how we'll do that?

In particular, as you know I think it's very important that we combine efforts with the existing library ports (including musl) in this space, from emscripten.

**Comment by jfbastien** [comment]
The master branch is straight musl, no changes, and updated semi-frequently (I'm thinking of just setting up a cron job which pulls from musl and pushes here). Any experimentation goes on in `*-prototype` branch, tucked away behind the "branches" button, with a README.md that explains this. I'm happy to update the current README.md to make this clearer: the landing page for the repo will also stay pristine that way.

Let me know if there's anything I can do to make this clearer: what you're saying is exactly my intent.

/cc @lukewagner to chime in, I think that's what I'd described on Friday?

**Comment by kripken** [comment]
Good to know, thanks.

But I still worry that there is a large disconnect here. While I think we agree that we should try to upstream as much as possible, as I mentioned, there is already a working port of musl in this space, in emscripten. So I am not sure what you mean to do in `*-prototype` branches, as "prototype" implies something early, initial, etc.?

**Comment by jfbastien** [comment]
I added readme.md to the landing branch to clarify things. Let me know if that's not clear enough, I'm happy to clarify further.
