### ISSUE TITLE
moving this repo under WebAssembly

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/musl#15]
As discussed in a recent PR it would probably make sense to move this project under the WebAssembly project.   @jfbastien please go ahead and do that whenever you get a chance.

**Comment by kripken** [comment]
When we discussed that in the past, the question came up of how official it is. Is this more official than the musl port in emscripten, in particular, and how do those relate to each other, etc. I don't think we made any decisions there?

**Comment by jfbastien** [comment]
I think @sbc100's goal is to progressively upstream to the musl repo? If so then it's as official can be, with the intent of fully deprecating when fully upstreamed. I think it's important to have a stand-alone libc which doesn't require emscripten and can work for non-JS embeddings, and I'd hope that it can Just Work for emscripten as well.

Would be good to hear from @dschuff and @lukewagner as well.

**Comment by kripken** [comment]
I wasn't aware we had a plan for this, but that sounds good. How would a musl port by itself work, though? would it also include the JS parts? or would we just define an interface to them (the syscall interface)? Do we have a plan for using that in emscripten?

**Comment by jfbastien** [comment]
We can't upstream the JS bits if the musl folks don't want them :)

Let's discuss this at the upcoming face-to-face?

**Comment by sbc100** [comment]
I think it would be great to have something that could be used both within emscripten and outside/standalone.  Having a well defined syscall that different consumers can share would also be very useful.  @kripken what do you think about have emscripten pull in musl (and compiler-rt for that matter) as separate git repositories rather containing a copy of them?  I think that might be the first step towards a convergence.

**Comment by kripken** [comment]
@jfbastien Have we checked what the musl policy is? I believe they have x86 assembly etc. for some things, so why not JS ("assembly language of the web" ;) ). If not, then we'd need another repo for the js stuff, which could be weird.

@sbc100 in general that sounds good. but for musl the details might be tricky. emscripten purposefully doesn't use the linux syscall interface for everything, we just implement things like time/date directly in js, for efficiency. maybe we should revisit that. but stuff like that would need to be figured out - given the web has a ton of stuff already, shipping all of musl may be wasteful.

**Comment by jfbastien** [comment]
> @jfbastien Have we checked what the musl policy is? I believe they have x86 assembly etc. for some things, so why not JS ("assembly language of the web" ;) ). If not, then we'd need another repo for the js stuff, which could be weird.

I'd think that asking on the emailing list would clarify this best. I don't think everyone will agree that JS is assembly, even if you "use asm" 😉 

Let's discuss in person, and figure out what we want to do exactly, and how. No need to create noise on the musl list before.

> @sbc100 in general that sounds good. but for musl the details might be tricky. emscripten purposefully doesn't use the linux syscall interface for everything, we just implement things like time/date directly in js, for efficiency. maybe we should revisit that. but stuff like that would need to be figured out - given the web has a ton of stuff already, shipping all of musl may be wasteful.

I think we can share the same sources, and potentially build differently for different use cases? e.g. if you don't use LOCALE we could have a build without it, or use some tooling to strip it out, or have it as a separate `.wasm` for all users, etc.

**Comment by karwa** [comment]
@sbc100  curious observer here: what do these plans look like today?

**Comment by sbc100** [comment]
This repo is no longer active. wasi-sysroot is the logical successor: https://github.com/CraneStation/wasi-sysroot
