### ISSUE TITLE
Building with make

### ISSUE THREAD

**Issue by ElvishJerricco** [WebAssembly/musl#27]
I'm trying to keep a kosher cross compilation story, so my toolchain just has `PREFIX-TOOLNAME` for all the tools; e.g. `wasm32-unknown-unknown-wasm-cc` is a wrapper script that passes `-target wasm32-unknown-unknown-wasm` and whatnot to clang. `make all` fails to use `wasm32-unknown-unknown-wasm-ar`, instead expecting `ar`.

EDIT: Of course `CC=wasm32-unknown-unknown-wasm-cc`, and other environment variables, including `AR=...`. `$RANLIB` or `wasm32-unknown-unknown-wasm-ranlib` are also not used.

If I manually symlink it under the name `ar`, this is how far I get:

```bash
./configure --prefix=... --build=x86_64-unknown-linux-gnu --host=wasm32-unknown-unknown-wasm
make all
```

```
src/stdio/vfwprintf.c:195:22: error: passing 'int [2]' to parameter of type 'const wchar_t *' (aka 'const unsigned int *') converts between pointers to integer
      types with different sign [-Werror,-Wpointer-sign]
                litpct = wcsspn(s, L"%")/2; /* Optimize %%%% runs */
```

among a bunch of other warnings.

---

FWIW, I'm using these exact steps with other targets (without the extra `ar` symlink), and musl cross compiles to those just fine.

Clang: d8024668
LLVM: 0c61ae79
LLD: ddc8eea6

**Comment by ElvishJerricco** [comment]
Apparently you need to set the `CROSS_COMPILE` variable to get those tools correctly, which I didn't need to do on other versions of musl. Regardless, the `vfwprintf.c` error still occurs.

**Comment by sbc100** [comment]
I've just been creating a config.mak manual and it seems to work.  e.g.:

```
sysroot=/home/sbc/dev/wasm/waterfall/src/work/wasm-install/sysroot
prefix=$(sysroot)                                                                
exec_prefix=$(sysroot)                                                           
ARCH=wasm32                                                                      
CC=/home/sbc/dev/wasm/waterfall/src/work/wasm-install/bin/clang 
AR=/home/sbc/dev/wasm/waterfall/src/work/wasm-install/bin/llvm-ar
RANLIB=/sbc/dev/wasm/waterfall/src/work/wasm-install/bin/llvm-ranlib
CFLAGS=-target wasm32-unknown-unknown-wasm --sysroot=$(sysroot)  
```

If you use the above or similar (rather than the configure generated one that include all the extra -Werror stuff) then the build should complete.

When we build musl on the wasm waterfall we use libc.py build script (since it needs to work on windows too) which enables -Werror but explitly disables -Wpointer-sign and many other warning.

**Comment by sbc100** [comment]
This repo is no longer active. wasi-sysroot is the logical successor: https://github.com/CraneStation/wasi-sysroot
