### ISSUE TITLE
What's the plan for blocking syscalls?

### ISSUE THREAD

**Issue by ElvishJerricco** [WebAssembly/musl#28]
The browser won't let the main thread block, so how is this going to implement e.g. `sleep`? For reference, in Emscripten, `sleep(10);` will peg your CPU at 100% for 10 seconds, which I'd consider unacceptable in the long term.

I had a thought about using a sort of kernel <-> process model. Run WebAssembly modules in a WebWorker (the "process") and send syscalls to the main thread (the "kernel"). For blocking syscalls, use the new `Atomics` API (which would eventually be replaced by WebAssembly's planned atomics instructions) to wait until the main thread responds.

**Comment by jfbastien** [comment]
`Atomics.wait` doesn't work on the main thread for some browsers, through the following:
https://tc39.github.io/ecma262/#sec-agentcansuspend

**Comment by ElvishJerricco** [comment]
@jfbastien Right. That's why I suggested running the process in a WebWorker, and interacting with browser APIs over a syscall interface. The model I'm thinking of is quite similar to [browsix](https://browsix.org/).

**Comment by jfbastien** [comment]
There's not really a plan for this repo at this point in time, but it's indeed something that'll need to be figured out eventually. Moving off the main thread has downsides too, it isn't a clear win.

**Comment by ElvishJerricco** [comment]
The main downside is probably the indirection in calling browser APIs. Having to send a message back to the main thread, telling it to read the relevant memory from the `SharedArrayBuffer` and execute some command is not as cheap as calling a function from the `Table`.

I know this is a few logical steps away, but it may help guide the intuition about performance: There's a Haskell library called `jsaddle` which abstracts the browser API so that you can call it in a variety of ways. When compiling Haskell to JS,`jsaddle` uses a JS FFI to talk to the browser directly. And when compiling Haskell to a native mobile app, it marshals data in and out in much the same way that I suggested above, but through the C FFIs of both languages.

The conclusion I've drawn having used this in production is that the marshaling and indirection involved is surprisingly cheap. The performance cost of the marshaling was totally negligible compared to the performance benefit we got for compiling to native code. And I'd expect to be able to get even faster marshaling being in the same VM and sharing access to the heap.

---

And anyway, it doesn't seem like we have a lot of choices. I don't really think we can consider synchronous syscalls optional, considering the point of WebAssembly is to support C / C++ code bases with minimal porting work. Though I suppose we can just let the user decide whether to run the program in a WebWorker, and just have these sycalls fail when the program runs in the main thread.

**Comment by jfbastien** [comment]
As a comparison, PNaCl was out-of-process and did FFI to communicate to the main thread. The cost was acceptable often, except when it wasn't. WebAssembly as embedded on the web is in-process and can be on main thread because of that type of experience. Keeping the option to be on or off main thread seems desirable.
