### ISSUE TITLE
Add Java(JVM)/C#(CLI) backend support? Not only javascript?

### ISSUE THREAD

**Issue by lygstate** [WebAssembly/musl#33]

**Comment by jfbastien** [comment]
Are you volunteering to do so? The JavaScript support isn't very solid, and I'd focus efforts on making that one great first.

**Comment by lygstate** [comment]
@jfbastien I am interested in JVM backend, (Android need it) but I don't know where to  start:)

**Comment by mikevoronov** [comment]
@lygstate [Asmble](https://github.com/cretz/asmble) could be a good starting point.
