### ISSUE TITLE
dlopen refcount == 0 ?

### ISSUE THREAD

**Issue by pepyakin** [WebAssembly/musl#38]
Why refcount starts with 0 here?
https://github.com/jfbastien/musl/blob/0c827335e4e1a6000d6167ba83ea633cbedc10b8/arch/wasm32/wasm.js#L649

IIUC, dlopen+dlclose pair will lead to a memory leak.

**Comment by sbc100** [comment]
This repo is no longer active. wasi-sysroot is the logical successor: https://github.com/CraneStation/wasi-sysroot
