### ISSUE TITLE
long double should be quad float

### ISSUE THREAD

**Issue by cag** [WebAssembly/musl#54]
From https://webassembly.org/docs/c-and-c++/:

> float and double are the IEEE 754-2008 single- and double-precision types, which are native in WebAssembly. long double is the IEEE 754-2008 quad-precision type, which is a software-emulated type. WebAssembly does not have a builtin quad-precision type or associated operators. The long double type here is software-emulated in library code linked into WebAssembly applications that need it.

This means arch/wasm32/bits/float.h should have:

```c
#define FLT_EVAL_METHOD 0

#define LDBL_TRUE_MIN 6.47517511943802511092443895822764655e-4966L
#define LDBL_MIN 3.36210314311209350626267781732175260e-4932L
#define LDBL_MAX 1.18973149535723176508575932662800702e+4932L
#define LDBL_EPSILON 1.92592994438723585305597794258492732e-34L

#define LDBL_MANT_DIG 113
#define LDBL_MIN_EXP (-16381)
#define LDBL_MAX_EXP 16384

#define LDBL_DIG 33
#define LDBL_MIN_10_EXP (-4931)
#define LDBL_MAX_10_EXP 4932

#define DECIMAL_DIG 36
```

**Comment by sbc100** [comment]
Sounds right.  Would you be interested in creating a PR to change this?
