### ISSUE TITLE
--compile-to-wasm is broken: "weak symbols not supported yet"

### ISSUE THREAD

**Issue by ElvishJerricco** [WebAssembly/musl#7]
Attempting to build with `--compile-to-wasm` results in a backend error:

```bash
$ python libc.py --compile-to-wasm --clang_dir path/to/clang/bin --musl `pwd` --binaryen_dir path/to/binaryen/bin --verbose
```

```
fatal error: error in backend: weak symbols not supported yet
```

The failing command was:

```bash
path/to/clang/bin/clang -target wasm32-unknown-unknown-wasm \
  -Os -c -nostdinc -I [...]/musl/include -I [...]/musl/src/internal -I [...]/musl/arch/wasm32 \
  -Wno-incompatible-library-redeclaration -Wno-shift-op-parentheses -Wno-ignored-attributes \
  -Wno-bitwise-op-parentheses -Wno-pointer-sign -Wno-unknown-pragmas \
  [...]/musl/src/ctype/isalnum.c
```

---

- LLVM: llvm-mirror/llvm@9c490091f2ff9286c76e9c490f05ff744a60b0c8
- Clang: llvm-mirror/clang@cdc846bf68eaeabea7f515b0daa3657777924c0f

---

PS: Is `binaryen_dir` really necessary when using `--compile-to-wasm`? I don't think it should be, but it's still a required argument.

---

CC @sbc100

**Comment by sbc100** [comment]
This should be fixed on llvm head.
We build this on the waterfall for example:  https://wasm-stat.us/builders/linux/builds/21283/steps/musl/logs/stdio

**Comment by ElvishJerricco** [comment]
I guess that's what I get for using an LLVM one week old =P I'll confirm that it works.

**Comment by ElvishJerricco** [comment]
Fixed on LLVM head. Closing
